### ISSUE TITLE
Missing config logfiles section

### ISSUE THREAD

**Issue by indepth666** [indepth666/py3rcon#4]
The logfile part of the json config file is missing, can you make a pull request with the complete file so we can merge it?

If it's not done yet let me know I can do it.

Thanks!

**Comment by ole1986** [comment]
Thank you for your advice

can you please update the example config from my repository?
I have already committed other things which should not be included since I have not fully tested.

https://github.com/ole1986/python3rcon/blob/master/configexample.json
https://github.com/ole1986/python3rcon/blob/master/README.md

Thank you

**Comment by indepth666** [comment]
Yes it will be done  tonight

**Comment by indepth666** [comment]
I think we should try to find a better name for the project. pythonBERCon sound stupid. 

I find your pyrcon name better but since it alreayd exist (https://pypi.python.org/pypi/pyrcon/) we need to find something else. 

Python3rcon may be nice but maybe a little too long? 
Let me know.

**Comment by ole1986** [comment]
I fully agree,
Unfortunately I did not checked before creating the client if something similar already exist.

How about "py3rcon"?

So it would be py3rcon-gui when ppl. have questions about the upcoming GUI (ncurses) :-)

**Comment by indepth666** [comment]
Py3rcon it will be!
Good idea with the ncurse gui!

**Comment by ole1986** [comment]
ok - just renamed the CLI plus pid and amended the description.

Also finalized the server command module. Will do a pull request shortly
version: 0.1b
